GET http://localhost:3000/dev/api/v1/clients

###

POST http://localhost:3000/dev/api/v1/clients
Content-Type: application/json

{
  "name": "Learnquest",
  "contact": "José Bragado",
  "email": "jose.bragado@learnquest.com"
}

###
POST http://localhost:3000/dev/api/v1/clients
Content-Type: application/json

{
  "name": "Grupo Xcaret",
  "contact": "Evelyn Escalante ",
  "email": "eescalante@xcaret.com"
}

###

POST http://localhost:3000/dev/api/v1/clients
Content-Type: application/json

{
  "name": "Accenture",
  "contact": "Elsa Fuentes",
  "email": "e.fuentes.martinez@accenture.com"
}

###

POST http://localhost:3000/dev/api/v1/clients
Content-Type: application/json

{
  "name": "Palace Resorts",
  "contact": "Iván Villafán",
  "email": "ivahernandez@palaceresorts.com"
}
