GET http://localhost:3000/dev/api/v1/courses

###

PUT http://localhost:3000/dev/api/v1/courses/63069415b4479c4174d04875
Content-Type: application/json

{
  "name": "Introducción a Project Management",
  "category": "630672e53b709b4e4e8efb47",
  "duration": "",
  "has_certification": true,
  "certification": "Project Management Professional",
  "partner": "63066997c3c2cb987fd5d8f4"
}

###

POST http://localhost:3000/dev/api/v1/courses
Content-Type: application/json

{
  "name": "Introducción a Project Management",
  "category": "630672e53b709b4e4e8efb47",
  "duration": "2 días"
}

###

POST http://localhost:3000/dev/api/v1/courses
Content-Type: application/json

{
  "name": "Introducción a Project Management",
  "category": "630672e53b709b4e4e8efb47",
  "duration": "2 dias",
  "has_certification": true,
  "certification": "Project Management Professional",
  "partner": "63066997c3c2cb987fd5d8f4"
}

